### ISSUE TITLE
Doesn't correctly determine if dark mode is on

### ISSUE THREAD

**Issue by iMaddin** [NSRover/NinjaMode#1]
When dark mode is already on and you then launch the app to toggle between the modes nothing happens. That's because the check in `-refreshDarkMode` fails.

You can use this line instead to successfully check if dark mode is on:

`NSString *value = [[NSUserDefaults standardUserDefaults] stringForKey:@"AppleInterfaceStyle"];`

**Comment by andrewpmiller** [comment]
@iMaddin is right. I think that the way you're doing it also leaves the UI in a very unstable condition: In my case, the dock got "stuck" in dark mode, and would not change back. And the system prefs would not change when toggling the check box. I replaced the line with what is suggested above, and the rebuilt app works correctly - and doesn't corrupt the system prefs. At least this is the case with 10.10.1.

**Comment by alexrosenfeld10** [comment]
https://github.com/NSRover/NinjaMode/pull/4 fixes this, this issue can now be closed
